// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package 


import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData },
		
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
"Hello World from templ at home in the dark!": 0,
}



var en_USIndex = []uint32{ // 2 elements
0x00000000,0x0000002c,
}// Size: 32 bytes



const en_USData string = "" + // Size: 44 bytes
"\x02Hello World from templ at home in the dark!"


// Total table size 76 bytes (0KiB); checksum: A1F10D25
