services:
  knov:
    build:
      context: ../..
      dockerfile: tools/docker_deployment/Dockerfile
    image: knov:latest
    container_name: knov
    restart: unless-stopped
    ports:
      - "1324:1324"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./themes:/app/themes
      - ./storage:/app/storage
      - ./logs:/app/logs
      - ./backups:/app/backups
