// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "summary": "Health check",
                "responses": {}
            }
        },
        "/api/themes": {
            "get": {
                "description": "Get current theme and available themes, or set new theme via query parameter",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "themes"
                ],
                "summary": "Get and set themes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Theme name to set (POST only)",
                        "name": "theme",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"current\":\"themename\",\"available\":[\"theme1\",\"theme2\"]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Get current theme and available themes, or set new theme via query parameter",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "themes"
                ],
                "summary": "Get and set themes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Theme name to set (POST only)",
                        "name": "theme",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"current\":\"themename\",\"available\":[\"theme1\",\"theme2\"]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "http://localhost:1324",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Knov API",
	Description:      "KNOV API \\n http://localhost:1324",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
