// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/config/getConfig": {
            "get": {
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get current configuration",
                "responses": {}
            }
        },
        "/api/config/getRepositoryURL": {
            "get": {
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get git repository URL",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/config/setConfig": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set configuration",
                "responses": {}
            }
        },
        "/api/config/setLanguage": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set language",
                "responses": {}
            }
        },
        "/api/config/setRepositoryURL": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Set git repository URL",
                "responses": {}
            }
        },
        "/api/files/content/{filepath}": {
            "get": {
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Get file content as html",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "filepath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/files/filter": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Filter files by metadata",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Metadata fields to filter on",
                        "name": "metadata[]",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter operators (equals, contains, greater, less, in)",
                        "name": "operator[]",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter values",
                        "name": "value[]",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Logic operators (and, or)",
                        "name": "logic[]",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter actions (include, exclude)",
                        "name": "action[]",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/files.File"
                            }
                        }
                    }
                }
            }
        },
        "/api/files/list": {
            "get": {
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Get all files",
                "responses": {}
            }
        },
        "/api/files/metadata": {
            "get": {
                "description": "Get metadata for a file by providing filepath as query parameter",
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Get metadata for a single file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "filepath",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/files.Metadata"
                        }
                    },
                    "400": {
                        "description": "missing filepath parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "metadata not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to get metadata",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Set metadata for a file using JSON payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Set metadata for a single file",
                "parameters": [
                    {
                        "description": "Metadata object",
                        "name": "metadata",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/files.Metadata"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "metadata saved",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "invalid json or missing path",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to save metadata",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/files/metadata/rebuild": {
            "post": {
                "description": "Creates metadata for all files that don't have metadata yet",
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Initialize/Rebuild metadata for all files",
                "responses": {
                    "200": {
                        "description": "metadata initialized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "failed to initialize metadata",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/git/history": {
            "get": {
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "git"
                ],
                "summary": "Get recently changed files",
                "responses": {}
            }
        },
        "/api/health": {
            "get": {
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {}
            }
        },
        "/api/testdata/clean": {
            "post": {
                "description": "Removes all test data files and metadata",
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "testdata"
                ],
                "summary": "Clean test data",
                "responses": {
                    "200": {
                        "description": "{\"status\":\"ok\",\"message\":\"test data cleaned\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/testdata/setup": {
            "post": {
                "description": "Creates test files, git operations, and metadata for testing",
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "testdata"
                ],
                "summary": "Setup test data",
                "responses": {
                    "200": {
                        "description": "{\"status\":\"ok\",\"message\":\"test data setup completed\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/themes/getAllThemes": {
            "get": {
                "description": "Get current theme and available themes",
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "themes"
                ],
                "summary": "Get themes",
                "responses": {
                    "200": {
                        "description": "{\"current\":\"themename\",\"available\":[\"theme1\",\"theme2\"]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/themes/setTheme": {
            "post": {
                "description": "Set new theme via form parameter",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "tags": [
                    "themes"
                ],
                "summary": "Set theme",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Theme name to set",
                        "name": "theme",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "303": {
                        "description": "Redirect to settings page"
                    }
                }
            }
        }
    },
    "definitions": {
        "files.File": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/files.Metadata"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "files.Metadata": {
            "type": "object",
            "properties": {
                "ancestor": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "boards": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "folders": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "kids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lastEdited": {
                    "type": "string"
                },
                "linksToHere": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "parents": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "path": {
                    "type": "string"
                },
                "priority": {
                    "$ref": "#/definitions/files.priority"
                },
                "project": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/files.status"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "targetDate": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/files.filetype"
                },
                "usedLinks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "files.filetype": {
            "type": "string",
            "enum": [
                "todo",
                "note",
                "journal"
            ],
            "x-enum-varnames": [
                "FileTypeTodo",
                "FileTypeNote",
                "FileTypeJournal"
            ]
        },
        "files.priority": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high"
            ],
            "x-enum-varnames": [
                "PriorityLow",
                "PriorityMedium",
                "PriorityHigh"
            ]
        },
        "files.status": {
            "type": "string",
            "enum": [
                "draft",
                "published",
                "archived"
            ],
            "x-enum-varnames": [
                "StatusDraft",
                "StatusPublished",
                "StatusArchived"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:1324",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Knov API",
	Description:      "KNOV API \\n http://localhost:1324",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
