// Command genenv regenerates .env.example from configmanager.EnvVarDefs, so the example
// file can't drift from the code that actually reads these variables. Run via `make env-example`.
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"knov/internal/configmanager"
)

const separatorWidth = 80

// wrapWidth is the target line length for word-wrapped comment text, not counting the "# "
// prefix - chosen to keep .env.example comments readable without relying on editor soft-wrap.
const wrapWidth = 96

func main() {
	var buf bytes.Buffer
	buf.WriteString("# generated by `make env-example` (see tools/genenv) from internal/configmanager/envdefs.go\n")
	buf.WriteString("# for a more readable overview go to /system/environment\n")
	buf.WriteString("# do not edit by hand - your changes will be overwritten\n\n")

	category := ""
	for i, def := range configmanager.EnvVarDefs {
		if def.Category != category {
			if i > 0 {
				buf.WriteString("\n")
			}
			category = def.Category
			buf.WriteString(sectionHeader(category))
			if desc := configmanager.EnvCategoryDescriptions[category]; desc != "" {
				writeComment(&buf, desc)
				buf.WriteString("#\n")
			}
		}

		writeComment(&buf, def.Description)
		if len(def.AvailableValues) > 0 {
			fmt.Fprintf(&buf, "# options: %s\n", strings.Join(def.AvailableValues, ", "))
		}
		fmt.Fprintf(&buf, "%s=%s\n", def.Key, def.Default)
	}

	if err := os.WriteFile(".env.example", buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "genenv: %v\n", err)
		os.Exit(1)
	}
}

// sectionHeader renders "# ── category ──...──" padded to separatorWidth, matching the
// existing .env.example style.
func sectionHeader(category string) string {
	prefix := "# ── " + category + " "
	dashes := separatorWidth - len(prefix)
	if dashes < 0 {
		dashes = 0
	}
	return prefix + strings.Repeat("─", dashes) + "\n"
}

// writeComment writes text as one or more "# "-prefixed comment lines - shared by var
// descriptions and category descriptions (configmanager.EnvCategoryDescriptions). Descriptions
// are written as continuous prose in envdefs.go and word-wrapped here to wrapWidth; a paragraph
// is instead emitted verbatim (e.g. the aligned "Examples:" block on KNOV_BACKUP_AUTO_PROFILES)
// when it was deliberately laid out across multiple lines - detected by an indented
// continuation line, which word-wrapping would otherwise ruin. Paragraphs are separated by a
// blank line in the source ("\n\n") and reproduced as a bare "#" between them.
func writeComment(buf *bytes.Buffer, text string) {
	for i, para := range strings.Split(text, "\n\n") {
		if i > 0 {
			buf.WriteString("#\n")
		}
		lines := strings.Split(para, "\n")
		if isPreformatted(lines) {
			for _, line := range lines {
				fmt.Fprintf(buf, "# %s\n", line)
			}
			continue
		}
		for _, line := range wrapText(strings.Join(lines, " "), wrapWidth) {
			fmt.Fprintf(buf, "# %s\n", line)
		}
	}
}

// isPreformatted reports whether a paragraph was deliberately laid out across multiple lines
// (indented continuation lines) rather than just wrapped prose that happens to span lines.
func isPreformatted(lines []string) bool {
	if len(lines) < 2 {
		return false
	}
	for _, line := range lines[1:] {
		if strings.HasPrefix(line, " ") || strings.HasPrefix(line, "\t") {
			return true
		}
	}
	return false
}

// wrapText greedily word-wraps text to width-character lines.
func wrapText(text string, width int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return []string{""}
	}
	lines := []string{words[0]}
	for _, w := range words[1:] {
		last := lines[len(lines)-1]
		if len(last)+1+len(w) > width {
			lines = append(lines, w)
			continue
		}
		lines[len(lines)-1] = last + " " + w
	}
	return lines
}
