// Command genenv regenerates .env.example from configmanager.EnvVarDefs, so the example
// file can't drift from the code that actually reads these variables. Run via `make env-example`.
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"knov/internal/configmanager"
)

const separatorWidth = 80

func main() {
	var buf bytes.Buffer
	buf.WriteString("# generated by `make env-example` (see tools/genenv) from internal/configmanager/envdefs.go\n")
	buf.WriteString("# do not edit by hand - your changes will be overwritten\n\n")

	category := ""
	for i, def := range configmanager.EnvVarDefs {
		if def.Category != category {
			if i > 0 {
				buf.WriteString("\n")
			}
			category = def.Category
			buf.WriteString(sectionHeader(category))
		}

		for _, line := range strings.Split(def.Description, "\n") {
			fmt.Fprintf(&buf, "# %s\n", line)
		}
		if len(def.AvailableValues) > 0 {
			fmt.Fprintf(&buf, "# options: %s\n", strings.Join(def.AvailableValues, ", "))
		}
		fmt.Fprintf(&buf, "%s=%s\n", def.Key, def.Default)
	}

	if err := os.WriteFile(".env.example", buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "genenv: %v\n", err)
		os.Exit(1)
	}
}

// sectionHeader renders "# ── category ──...──" padded to separatorWidth, matching the
// existing .env.example style.
func sectionHeader(category string) string {
	prefix := "# ── " + category + " "
	dashes := separatorWidth - len(prefix)
	if dashes < 0 {
		dashes = 0
	}
	return prefix + strings.Repeat("─", dashes) + "\n"
}
