// Command gentemplatedocs regenerates docs/template_data.md from the struct
// definitions in internal/thememanager, so the reference stays in sync with
// the code instead of being hand-maintained. Run via `make docs-templatedata`.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"sort"
	"strings"
)

type field struct {
	Name string
	Type string
	Note string
}

type structInfo struct {
	Name   string
	Fields []field
	order  int
}

func main() {
	fset := token.NewFileSet()
	files := []string{
		"internal/thememanager/template_data.go",
		"internal/thememanager/system.go",
	}

	structs := map[string]*structInfo{}
	order := 0

	for _, path := range files {
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gentemplatedocs: %v\n", err)
			os.Exit(1)
		}

		for _, decl := range f.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				if ts.Name.Name != "BaseTemplateData" && !strings.HasSuffix(ts.Name.Name, "Data") {
					continue
				}
				if ts.Name.Name == "PageData" {
					continue
				}

				info := &structInfo{Name: ts.Name.Name, order: order}
				order++

				for _, f := range st.Fields.List {
					typeStr := exprString(fset, f.Type)
					note := commentText(f.Doc, f.Comment)

					if len(f.Names) == 0 {
						info.Fields = append(info.Fields, field{Name: typeStr, Type: "(embedded)", Note: note})
						continue
					}
					for _, n := range f.Names {
						info.Fields = append(info.Fields, field{Name: n.Name, Type: typeStr, Note: note})
					}
				}

				structs[ts.Name.Name] = info
			}
		}
	}

	names := make([]string, 0, len(structs))
	for name := range structs {
		names = append(names, name)
	}
	sort.Slice(names, func(i, j int) bool {
		return structs[names[i]].order < structs[names[j]].order
	})

	var buf bytes.Buffer
	buf.WriteString("# Template Data Reference\n\n")
	buf.WriteString("Generated by `make docs-templatedata` (see `tools/gentemplatedocs`) from the struct definitions in `internal/thememanager` — do not edit by hand.\n\n")
	buf.WriteString("Every page template receives a `PageData[T]`: the fields under **BaseTemplateData** are always available at the template's top level (e.g. `.Title`), and `.Data` holds the page-specific payload listed under that page's struct (e.g. `.Data.FilePath`).\n\n")

	for _, name := range names {
		info := structs[name]
		buf.WriteString("## " + info.Name + "\n\n")
		if len(info.Fields) == 0 {
			buf.WriteString("_no fields_\n\n")
			continue
		}
		buf.WriteString("| Field | Type | Notes |\n|---|---|---|\n")
		for _, fl := range info.Fields {
			buf.WriteString(fmt.Sprintf("| %s | `%s` | %s |\n", fl.Name, fl.Type, fl.Note))
		}
		buf.WriteString("\n")
	}

	if err := os.WriteFile("docs/template_data.md", buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "gentemplatedocs: %v\n", err)
		os.Exit(1)
	}
}

func exprString(fset *token.FileSet, expr ast.Expr) string {
	var buf bytes.Buffer
	_ = printer.Fprint(&buf, fset, expr)
	return buf.String()
}

func commentText(groups ...*ast.CommentGroup) string {
	for _, g := range groups {
		if g == nil {
			continue
		}
		text := strings.TrimSpace(g.Text())
		text = strings.ReplaceAll(text, "\n", " ")
		if text != "" {
			return text
		}
	}
	return ""
}
